src/Vjezba/Vjezba.Web/Controllers/MessageController.cs
using Ninject;
using Project.DAL.Repository;
using Project.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Project.Web.Controllers
{
    [Authorize]
    [RoutePrefix("Message")]
    public class MessageController : BaseController
    {
        [Inject]
        public MessageRepository MessageRepository { get; set; }

        // GET: Messages
        public ActionResult Index()
        {
            return View(MessageRepository.GetList(userId));
        }

        [HttpPost]
        [Route("Delete")]
        public JsonResult Delete(int id)
        {
            this.MessageRepository.Hide(id, userId, true);

            return new JsonResult() { Data = "OK", JsonRequestBehavior = JsonRequestBehavior.AllowGet };
        }

        [Route("{id}")]
        public ActionResult Details(int id)
        {
            this.MessageRepository.MarkAsRead(id, userId, autoSave: true);
            return View(this.MessageRepository.Find(id));
        }

        [Route("Send")]
        public ActionResult Send(Message model)
        {
            bool? success = false;
            if (ModelState.IsValid)
            {
                model.ReceiverID = model.CreatedById;
                this.MessageRepository.Add(model, userId, autoSave: true);
                saveToLogFile("Message sent: " + this.MessageRepository.GetList(userId).OrderByDescending(p => p.ID).FirstOrDefault().ID);
                success = true;
            }
            if (success.Value)
            {
                TempData["Success"] = "Message sent.";
            }
            else
            {
                TempData["Error"] = "Message failed.";
            }
            return RedirectToAction("Index");
        }
    }
}

src/Vjezba/Vjezba.Web/Controllers/TripController.cs
using Ninject;
using Project.DAL.Repository;
using Project.Model;
using Project.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace Project.Web.Controllers
{
    //[RoutePrefix("Trip")]
    public class TripController : BaseController
    {
        [Inject]
        public TripRepository TripRepository { get; set; }

        [Inject]
        public CityRepository CityRepository { get; set; }

        [Inject]
        public CountryRepository CountryRepository { get; set; }

        [Inject]
        public ReportRepository ReportRepository { get; set; }

        [Inject]
        public FavoriteRepository FavoriteRepository { get; set; }

        [Inject]
        public MessageRepository MessageRepository { get; set; }

        [Inject]
        public BookingRepository BookingRepository { get; set; }

        [Inject]
        public PaymentMethodRepository PaymentMethodRepository { get; set; }

        [Inject]
        public TransactionRepository TransactionRepository { get; set; }

        [Inject]
        public UserRepository UserRepository { get; set; }

        // GET: Trip
        public ActionResult Index()
        {
            // TODO: Show active list only
            return this.View(this.TripRepository.GetActiveList());
        }

        //[Route("IndexAjax")]
        [HttpPost]
        public ActionResult IndexAjax(TripFilterModel model)
        {
            return PartialView("_IndexTable", this.TripRepository.GetActiveList(model));
        }

        //[Route("{id}")]
        public ActionResult Details(int id)
        {
            Trip trip = this.TripRepository.Find(id);
            bool isFavorite = false;

            PaymentMethod paymentMethod = null;
            int? bookingID = null;

            if (userId != null)
            {
                var booking = BookingRepository.Find(userId, trip.ID);
                if (booking != null)
                {
                    bookingID = booking.ID;
                }

                paymentMethod = PaymentMethodRepository.FindByUserId(userId);

                isFavorite = FavoriteRepository.IsFavorited(userId, id);
            }

            TripDetailsModel details = new TripDetailsModel
            {
                ID = trip.ID,
                Title = trip.Title,
                Description = trip.Description,
                Price = trip.Price,
                CityID = trip.CityID,
                ImageUrl = trip.ImageUrl,
                CreatedById = trip.CreatedById,
                UserCreated = trip.UserCreated,
                City = trip.City,
                BookingID = bookingID,
                DepartsAt = trip.DepartsAt,
                ReturnsAt = trip.ReturnsAt,
                PaymentMethod = paymentMethod,
                User = UserRepository.Find(userId),
                IsFavorite = isFavorite
            };

            return View(details);
        }

        [Authorize]
        [HttpPost]
        //[Route("Contact")]
        public ActionResult Contact(Message model)
        {
            if (ModelState.IsValid)
            {
                this.MessageRepository.Add(model, userId, autoSave: true);
                saveToLogFile("Message sent: " + this.MessageRepository.GetList(userId).OrderByDescending(p => p.ID).FirstOrDefault().ID);
                TempData["Success"] = "Message sent.";
            }
            else
            {
                TempData["Error"] = "Message failed.";
            }
            var trip = TripRepository.Find(model.TripID.Value);
            return RedirectToAction("Details", new { id = model.TripID.Value });
        }

        [Authorize]
        [HttpPost]
        //[Route("Report")]
        public ActionResult Report(Report model)
        {
            if (ModelState.IsValid)
            {
                if (this.ReportRepository.isReported(userId, model.TripID.Value))
                {
                    TempData["Error"] = "Already reported.";
                }
                else
                {
                    this.ReportRepository.Add(model, userId, autoSave: true);
                    saveToLogFile("Reported: " + this.ReportRepository.GetList().OrderByDescending(p => p.ID).FirstOrDefault().ID);

                    TempData["Success"] = "Report sent.";
                }
            }
            else
            {
                TempData["Error"] = "Report failed.";
            }

            var trip = TripRepository.Find(model.TripID.Value);
            return RedirectToAction("Details", new { id = model.TripID.Value });
        }

        [Authorize]
        [HttpPost]
        //[Route("Booking")]
        public ActionResult Booking(TripDetailsBooking model)
        {
            if (this.BookingRepository.IsBooked(userId, model.TripID.Value))
            {
                TempData["Error"] = "Already booked.";
            }
            else
            {
                PaymentMethod paymentMethod = null;

                if (model.HasPaymentMethod)
                {
                    paymentMethod = PaymentMethodRepository.FindByUserId(userId);
                    if (paymentMethod == null)
                    {
                        var maskedNumber = model.CardNumber.Substring(0, 4) + "********" + model.CardNumber.Substring(model.CardNumber.Count() - 4);
                        var hash = Convert.ToBase64String(MD5.Create().ComputeHash(Encoding.UTF8.GetBytes(model.CardNumber)));

                        model.CardNumber = null;

                        model.PaymentMethod.MaskedNumber = maskedNumber;
                        model.PaymentMethod.Token = hash;

                        PaymentMethodRepository.Add(model.PaymentMethod, userId, true);
                        paymentMethod = PaymentMethodRepository.FindByUserId(userId);
                    }
                }

                if (paymentMethod != null)
                {
                    var transaction = new Transaction
                    {
                        PaymentMethodID = paymentMethod.ID,
                        TripID = model.TripID,
                        CreatedById = userId,
                        TotalPrice = TripRepository.Find(model.TripID.Value).Price.Value
                    };

                    this.TransactionRepository.Add(transaction, userId, true);

                    model.TransactionID = this.TransactionRepository.GetList().OrderByDescending(p => p.ID).FirstOrDefault().ID;

                    var booking = new Booking
                    {
                        PhoneNumber = model.PhoneNumber,
                        FullName = model.FullName,
                        TransactionID = model.TransactionID,
                        TripID = model.TripID
                    };

                    this.BookingRepository.Add(booking, userId, autoSave: true);
                    var bookingId = this.BookingRepository.GetList().OrderByDescending(p => p.ID).FirstOrDefault().ID;
                    saveToLogFile("Booked: " + bookingId);

                    TempData["Success"] = "Booking completed";

                    return RedirectToAction("Details", "Booking", new { id = bookingId });
                }
                else
                {
                    TempData["Error"] = "Booking failed, no payment method for this user.";
                }
            }

            return RedirectToAction("Details", new { id = BookingRepository.Find(model.TripID.Value) });
        }

        [Authorize]
        //[Route("Create")]
        [HttpGet]
        public ActionResult Create()
        {
            this.FillDropDownValues();
            return View();
        }

        [Authorize]
        //[Route("Create")]
        [HttpPost]
        public ActionResult Create(Trip model, HttpPostedFileBase UploadedFile)
        {
            string guid = Guid.NewGuid().ToString();

            string path = Server.MapPath("~/Images/" + guid + "_" + UploadedFile.FileName);
            string relativePath = "Images/" + guid + "_" + UploadedFile.FileName;
            UploadedFile.SaveAs(path);

            model.ImageUrl = relativePath;
            model.City = CityRepository.Find(model.CityID.Value);
            model.City.Country = CountryRepository.Find(model.City.CountryID.Value);

            this.TripRepository.Add(model, userId, autoSave: true);

            saveToLogFile("Trip created: " + this.TripRepository.GetList().OrderByDescending(p => p.ID).FirstOrDefault().ID);

            return RedirectToAction("Index");
        }

        [HttpGet]
        //[ActionName("Edit")]
        public ActionResult Edit(int id)
        {
            this.FillDropDownValues();

            var model = this.TripRepository.Find(id);

            return View(model);
        }

        [HttpPost]
        //[ActionName("Edit")]
        public ActionResult EditPost(int id, HttpPostedFileBase UploadedFile)
        {
            var model = this.TripRepository.Find(id);

            if (UploadedFile != null)
            {
                string guid = Guid.NewGuid().ToString();

                string path = Server.MapPath("~/Images/" + guid + "_" + UploadedFile.FileName);
                string relativePath = "Images/" + guid + "_" + UploadedFile.FileName;
                UploadedFile.SaveAs(path);
                model.ImageUrl = relativePath;
            }

            var didUpdateModelSucceed = this.TryUpdateModel(model);

            if (didUpdateModelSucceed && ModelState.IsValid)
            {
                this.TripRepository.Update(model, autoSave: true);
                saveToLogFile("Trip edited: " + id);
                return RedirectToAction("Details", new { id = model.ID });
            }

            this.FillDropDownValues();
            return View(model);
        }

        [Authorize]
        //[Route("Favorite")]

src/Vjezba/Vjezba.Web/Views/Message/Details.cshtml
@using Microsoft.AspNet.Identity

@model Project.Model.Message

@{

    string senderFullName = null;
    string receiverFullName = null;

    if (Model.UserCreated.Id == Model.Trip.UserCreated.Id)
    {
        senderFullName = Model.UserCreated.AgencyName;
        receiverFullName = Model.Receiver.FirstName + " " + Model.Receiver.LastName;
    }
    else
    {
        receiverFullName = Model.Receiver.AgencyName;
        senderFullName = Model.UserCreated.FirstName + " " + Model.UserCreated.LastName;
    }



    if (Model.UserCreated.Id == User.Identity.GetUserId())
    {
        ViewBag.Title = "Message sent to " + receiverFullName;
    }
    else
    {
        ViewBag.Title = "Message received from " + senderFullName;
    }
}

<h1>@ViewBag.Title</h1>
<hr />

<br />

<div class="row">
    <div class="col-sm-12">
        <div class="panel panel-default">
            <div class="panel-heading">Message</div>
            <div class="panel-body">@Model.Description</div>
        </div>
    </div>
</div>

@if (Model.UserCreated.Id != User.Identity.GetUserId())
{
    <br />
    using (Html.BeginForm("Send", "Message"))
    {
        Model.Description = "";
        @Html.HiddenFor(model => model.TripID)
        @Html.HiddenFor(model => model.ReceiverID)
        @Html.HiddenFor(model => model.CreatedById)
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control multiline-text-medium", placeholder="Write a reply"} })
            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
        </div>
        <input type="submit" class="btn btn-primary pull-right" style="background:#00D49C; border:#00D49C" value="Reply" />
    }
    <br />
    <br />
}

<br />
<br />

<div class="row">
    <div class="col-sm-6">
        <div class="panel panel-default">
            <div class="panel-heading">
                Trip info
            </div>
            <div class="panel-body">
                <table class="table table-condensed table-details top-margin-small">
                    <tr class="borderless">
                        <th>Title</th>
                        <td><a href="@Url.Action("Details", "Trip", new { id = Model.Trip.ID })">@Model.Trip.Title</a></td>
                    </tr>
                    <tr>
                        <th>Location</th>
                        <td>@Model.Trip.City.Name (@Model.Trip.City.Country.Name)</td>
                    </tr>
                    <tr>
                        <th>Price</th>
                        <td><strong>@Model.Trip.Price EUR</strong></td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
    <div class="col-sm-6">
        <div class="panel panel-default">
            <div class="panel-heading">
                Sender info
            </div>
            <div class="panel-body">
                <table class="table table-condensed table-details contact-details">
                    <tr class="borderless">
                        <th>Full name</th>
                        <td>@senderFullName</td>
                    </tr>
                    <tr>
                        <th>Phone</th>
                        <td>@Model.UserCreated.PhoneNumber</td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
</div>

src/Vjezba/Vjezba.Web/Views/Message/Index.cshtml
@using Microsoft.AspNet.Identity

@model List<Project.Model.Message>

@{
    ViewBag.Title = "Messages";
}

<h1>@ViewBag.Title</h1>
<hr />


@if (TempData["Success"] != null)
{
    <div class="alert alert-success">
        <strong>Success!</strong> @TempData["Success"]
    </div>

}
@if (TempData["Error"] != null)
{
    <div class="alert alert-danger">
        <strong>Error!</strong> @TempData["Error"]
    </div>
}

<div class="row">
    <div class="col-sm-8 top-bottom-margin">
        <div class="input-group">
            <input type="text" class="form-control" placeholder="Search for...">
            <span class="input-group-btn">
                <button class="btn btn-primary" style="background:#00D49C; border:#00D49C" type="button">Go!</button>
            </span>
        </div>
    </div>
</div>

<br />


<ul class="nav nav-tabs">
    <li class="active"><a data-toggle="tab" href="#messages-received">Received</a></li>
    <li><a data-toggle="tab" href="#messages-sent">Sent</a></li>
</ul>

<br />

<div class="tab-content">
    <div id="messages-received" class="tab-pane fade in active">
        @Html.Partial("_MessagesPartial", @Model.Where(p => p.CreatedById != User.Identity.GetUserId()).ToList())
    </div>
    <div id="messages-sent" class="tab-pane fade">
        @Html.Partial("_MessagesPartial", @Model.Where(p => p.CreatedById == User.Identity.GetUserId()).ToList())
    </div>
</div>


<br />
<br />


@section scripts{

    <script type="text/javascript">

        function deleteMessage(link, msgId) {
            $.ajax({
                url: '@Url.Action("Delete")',
                data: { id: msgId },
                type: 'post',
                success: function (data) {
                    if (data == "OK") {
                        $(link).closest('a').remove();
                    }
                },
                error: function (xhr) {

                }
            });
        }

    </script>
}

src/Vjezba/Vjezba.Web/Views/Message/_MessagesPartial.cshtml
@using Microsoft.AspNet.Identity

@model List<Project.Model.Message>


@foreach (var msg in Model)
{
    var cssClass = "message-row";
    var condition = msg.Receiver.Id == User.Identity.GetUserId() && !msg.hasReceiverRead;
    if (condition)
    {
        cssClass += " " + "message-unread";
    }

    string senderFullName = null;
    string receiverFullName = null;

    if (msg.UserCreated.Id == msg.Trip.UserCreated.Id)
    {
        senderFullName = msg.UserCreated.AgencyName;
        receiverFullName = msg.Receiver.FirstName + " " + msg.Receiver.LastName;
    }
    else
    {
        receiverFullName = msg.Receiver.AgencyName;
        senderFullName = msg.UserCreated.FirstName + " " + msg.UserCreated.LastName;
    }


    <a href="@Url.Action("Details", new { id = msg.ID })" class="@cssClass">

        <div class="panel panel-default">
            <div class="panel-body">
                <div class="row">
                    <div class="col-sm-2 one-liner-elipsis">
                        @if (msg.UserCreated.Id == User.Identity.GetUserId())
                        {
                            <text>@receiverFullName</text>
                        }
                        else
                        {
                            <text>@senderFullName</text>
                        }
                    </div>
                    <div class="col-sm-8 one-liner-elipsis">
                        @msg.Trip.Title - @msg.Description
                    </div>
                    <div class="col-sm-1 one-liner-elipsis">
                        @msg.DateCreated.ToShortDateString()
                    </div>

                    <div class="col-sm-1">
                        <span class="glyphicon glyphicon-remove" aria-hidden="true" onclick="deleteMessage(this, @msg.ID); return false;"></span>
                    </div>

                </div>
            </div>
        </div>
    </a>

}